config/routes.rb
Bidstr::Application.routes.draw do
  devise_for :users

  root 'static_pages#home'

  resources :users do
  end

  resources :items do
    member do
      post :auction
    end
  end

  resources :bids do
  end

  resources :auctions do
    member do
      get :call
    end
  end

  

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  has_one :item
  has_many :users, through: :bids
  has_many :bids
  validates_presence_of :name

  def check_bid (value)
  	if self.bids.count > 0
  		result = value.to_d > self.bids.last.value ? true : false
  	else
  		result = true
  	end
  end

  def submit_bid (user_id, value)
  	bids.create!(user_id: user_id, auction_id: self.id, value: value)
  end

  def call
    item = self.item
    self.update_attributes(:active => false)
    if self.bids.count > 0
      price = self.bids.last.value
      user = self.bids.last.user_id
      item.update_attributes(:sold => true, :sold_price => price, :user_id => user)
    end
  end
end

app/models/bid.rb
class Bid < ActiveRecord::Base
	belongs_to :auction
	belongs_to :user
	validates_presence_of :value
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates_presence_of :name, :reserved_price
  validates_uniqueness_of :name
  belongs_to :auction
  belongs_to :user

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("lower(name) like lower(?)", "%#{query}%") 
  end

  def auction_status
  	if !self.auction.nil?
	  	status = self.auction.active
	  	case status
	  	when true
	  		"Active"
	  	when false
	  		"Closed"
	  	else
	  		"None"
	  	end
	  else
	  	"No Auction Yet"
	  end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :name, :email
  has_many :auctions, through: :bids
  has_many :bids

  def is_auctioneer?
  	current_user.auctioneer?
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

  private
    def check_admin
      unless current_user.auctioneer?
        redirect_to root_url
      end
    end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
	before_filter :authenticate_user!, except: [:index, :show]
	before_filter :check_admin, except: [:index, :show]

	def index
		@auctions = Auction.where(:active => true)
	end

	def new
		@auction = Auction.new
	end

	def create
	end

	def update
		@auction = Auction.find(params[:id])
		if @auction.update_attributes(auction_params)
			redirect_to @auction, :flash => {:success => "Updated auction!"}
		else
			redirect_to @auction
		end
	end

	def destroy
	end

	def show
		@auction = Auction.find(params[:id])
	end

	def call
		@auction = Auction.find(params[:id])
		@auction.call if @auction.active?
		redirect_to @auction, :flash => {:success => "Called auction"}
	end

	private

		def auction_params
			params.require(:auction).permit(:name, :active)
		end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
	before_filter :authenticate_user!, except: [:index]

	def index
		@bids = Bid.all
	end

	def new
		@bid = Bid.new
	end

	def create
		value = params[:bid][:value]
		auction = Auction.find(params[:bid][:auction_id])
		respond_to do |format|
			if auction.check_bid(value)
				auction.submit_bid(current_user.id, value)
				format.html { redirect_to auction, :flash => {:success => "Successful bid!"} }
				format.js
			else
				format.html { redirect_to auction, :flash => {:warning => "Bid was too low"} }
			end
		end
	end

	def destroy
	end

	private

		def bid_params
			params.require(:bid).permit(:user_id, :auction_id, :value)
		end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :check_admin, except: [:index, :show]

  def index
    if params[:search]
      @items = Item.search(params[:search]).order("created_at DESC")
    else
      @items = Item.all
    end
  end

  def new
  	@item = Item.new
  end

  def create
  	@item = Item.new(item_params)
  	if @item.save
  	  redirect_to @item, :flash => {:success => "Successfully created item!"}
  	else
  	  render :new
  	end
  end

  def edit
  	@item = Item.find(params[:id])
  end

  def update
  	@item = Item.find(params[:id])
	  if @item.update_attributes(item_params)
	    redirect_to @item, :flash => {:success => "Updated item!"}
	  else
	    render :edit
	  end
	end

  def show
  	@item = Item.find(params[:id])
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_url, :flash => {:success => "Destroyed bid!"}
  end

  def auction
    @item = Item.find(params[:id])
    auction = @item.create_auction(:name => "Auction for #{@item.name}", :active => true) if @item.auction.nil?
    @item.update_attribute(:auction_id, auction.id)
    redirect_to @item, :flash => {:success => "Item auctioned!"}
  end

  private

    def item_params
      params.require(:item).permit(:name, :reserved_price, :user_id, :auction_id, :sold_price, :sold )
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
		@auctions = Auction.where(:active => true).order('updated_at DESC').limit(5)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auctions/_auction.html.erb
<div class="col-lg-3 col-md-6 auction">
  <div class="thumbnail">
    <img src="http://placehold.it/800x500" alt="">
    <div class="caption">
      <h3><%= link_to auction.name, auction %></h3>
      <p><b>Current Bid:</b> <span id="current-bid"><%= auction.bids.count > 0 ? number_to_currency(auction.bids.last.value) : "None" %></span></p>
      <p><a href= <%= auction_path(auction) %> class="btn btn-primary">Bid Now!</a></p>
    </div>
  </div>
</div>

app/views/auctions/_bid_form.html.erb
<%= form_for(current_user.bids.build(auction_id: @auction.id), html: {class: "form-inline"}) do |f| %>
  <div class="form-group">
  	<%= f.label :value, class: "sr-only" %>
  	<%= f.text_field :value, class: "form-control", placeholder: "Enter Your Bid" %>
  	<%= f.hidden_field :auction_id, value: @auction.id %>
  </div>
  <%= f.submit "Submit Bid", class: "btn btn-primary" %>
<% end %>

app/views/auctions/index.html.erb
<div class="row">
	<div class="col-lg-3 col-lg-offset-4 text-center">
		<h1 class="thumbnail">Auctions</h1>
	</div>
</div>
<br>
<div id="container">
	<%= render @auctions %>
</div>

app/views/auctions/show.html.erb
<div class="container item-profile">
  <div class="row">
    <div class="col-lg-7 thumbnail item-card">
      <div class="row">
        <div class="col-md-3">
          <img src="http://placehold.it/200x200" alt="" class="img-responsive thumbnail">
        </div>
        <div class="col-md-8 thumbnail">
          <h3 class="inline" style="margin-top: 5px;"><%= @auction.name %></h3>
          <span style="display: block;" class="text-success">Auction <%= @auction.active ? "Live" : "Over" %></span>
          <hr>
          <p>Item for Sale: <%= link_to @auction.item.name, @auction.item if !@auction.item.nil? %></p>
          <p><b>Current Bid:</b> <span id="current-bid"><%= @auction.bids.count > 0 ? number_to_currency(@auction.bids.last.value) : "None" %></span></p>
          <% if user_signed_in? && current_user.auctioneer? && @auction.active? %>
            <%= link_to "Call Auction", call_auction_path(@auction), class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-lg-4 col-lg-offset-1 text-center thumbnail bid-card">
      <h2 class="thumbnail">Bid on It!</h2>
      <hr>
      <div class="row">
        <div class="col-lg-12">
          <%= render "bid_form" if user_signed_in? && @auction.active? %>
        </div>
      </div>
    </div>
  </div> <!-- end of row -->
</div>

app/views/bids/_bid.html.erb
<p><%= bid.user.name %> / <%= bid.auction.item.name %> / <%= bid.value %></p>

app/views/bids/create.js.erb
$("#current-bid").html('<%= @auction.bids.last.value %>')

app/views/bids/index.html.erb
<div>
	<%= render @bids %>
</div>

app/views/items/_auction_form.html.erb
<div id="auction_form" class="big-button">
  <% if user_signed_in? %>
  	<% if @item.auction.nil? %>
      <%= render 'start_auction' %>
    <% else %>
      <%= link_to "See Auction", auction_path(@item.auction) %>
    <% end %>
    <% if @item.sold? %>
      <p>Price: <%= @item.sold_price %></p>
    <% end %>
  <% end %>  
</div>

app/views/items/_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for @item do |f| %>

	    <% if @item.errors.any? %>
		    <div class="error_messages">
		      <h2><%= pluralize(@item.errors.count, "error") %>:</h2>
		      <ul>
		      <% @item.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
		      </ul>
		    </div>
	  	<% end %>

		  <div class="field">
	      <%= f.label :name, "Item Name" %>
	      <%= f.text_field :name %>

	      <%= f.label :reserved_price, "Item price" %>
	      <%= f.text_field :reserved_price %>
	    </div>

			<br/>

			<div class="actions">
	      <%= f.submit "Create item", class: "btn btn-large btn-primary" %>
	    </div>

    <% end %>
  </div>
</div>

app/views/items/_item.html.erb
<li class="list-group-item">
	<div>
	  <div class="inline-block">
	  	<img src="http://placehold.it/100x100" alt="" class="thumbnail">
	  </div>
	  <div class="inline-block" style="vertical-align: top;">
	  	<h4><%= link_to item.name, item %></h4>
	  	<br>
	  	<p>Reserved Price: <%= number_to_currency(item.reserved_price) %></p>
      <p>Sold: <%= item.sold ? "yes" : "no" %></p>
      <p>Auction Status: <%= item.auction_status %></p>
      <% if !item.auction.nil? && !item.auction.active? %>
      	<p>Sale Price: <%= number_to_currency(item.sold_price) %></p>
      	<p>Sold to: <%= link_to item.user.name, item.user %></p>
      	<p>Auction was a <%= (item.sold_price - item.reserved_price) > 0 ? "Success" : "Failure" %></p>
      <% end %>
	  </div>
  </div>
</li>

app/views/items/_start_auction.html.erb
<%= link_to "Start Auction", auction_item_path(@item.id), class: "btn btn-large btn-danger", method: "post" %>

app/views/items/index.html.erb
<div class="row">
	<div class="col-lg-2">
		<% if user_signed_in? && current_user.auctioneer? %>
			<br>
		  <p><%= link_to 'New Item', new_item_path, class: "btn btn-primary" %></p>
		<% end %>
	</div>
	<div class="col-lg-4 col-lg-offset-2 text-center">
		<h1 class="thumbnail">Items</h1>
	</div>
</div>

<div class="row">
	<div class="col-lg-4 col-lg-offset-4 hero-feature">
    <%= form_tag(items_path, :method => "get", :class => "form-inline", id: "search-form") do %>
	    <div class="form-group">
	    	<div class="col-lg-9">
		      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Items" %>
		      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
		           of using a Rails form helper -->
		    </div>
		      <%= submit_tag "Submit", class: "btn btn-success" %>
	    </div>
	  <% end %>
	  <hr>
	</div>
</div>

<div class="row">
	<div class="col-lg-4 col-lg-offset-4">
		<ul class="list-group">
  		<%= render @items %>
    </ul>
	</div>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render "form" %>

app/views/items/show.html.erb
<div class="container item-profile">
  <div class="row">
    <div class="col-md-2">
      <img src="http://placehold.it/200x200" alt="" class="img-responsive">
    </div>
    <div class="col-md-2">
      <h3 class="inline" style="margin-top: 5px;"><%= @item.name %></h3>
      <hr>
      <p>Reserved Price: <%= @item.reserved_price %></p>
      <p>Sold: <%= @item.sold ? "yes" : "no" %></p>
      <% if user_signed_in? %>
        <% if current_user.auctioneer? %>
          <%= render "auction_form" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
<div class="row">
  <div class="col-lg-12 text-center">
    <p>Copyright &copy; Company 2013 &middot; Facebook &middot; Twitter &middot; Google+</p>
  </div>
</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Bidstr</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Auctions", auctions_path %></a></li>
        <li><%= link_to "Items", items_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: "delete" %></li>
        <% else %>  
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bidstr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <section class="main container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
	<%= yield %>
  </section>
</body>
</html>

app/views/static_pages/home.html.erb
<div class="container">

  <div class="jumbotron hero-spacer">
    <h1>Welcome to Bidstr!</h1>
    <p>Want to place bids on random items?</p>
    <p><%= link_to "Join now!", new_user_registration_path, class: "btn btn-primary btn-large" %></p>
  </div>
  
  <hr>
  
  <div class="row">
    <div class="col-lg-12">
       <h3>Latest Auctions</h3>
    </div>
  </div><!-- /.row -->
  
  <div class="row">
    <%= render @auctions %>
  </div><!-- /.row -->
  
  <hr>
  
</div><!-- /.container -->